# Generated by Django 4.2.14 on 2024-07-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comments',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='pageURL',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterField(
            model_name='image',
            name='views',
            field=models.PositiveIntegerField(),
        ),
    ]
